# Use a imagem base adequada para seu projeto
FROM python:3.9

# Copie o arquivo de código para o contêiner
COPY app.py /app.py

# Comando para executar o código quando o contêiner iniciar
CMD ["python", "/app.py"]
